package com.github.project;

public enum MovieFilter {
    FILTER_BY_YEAR_LESS, FILTER_BY_YEAR_MORE, FILTER_BY_GENRE_NAME, FILTER_BY_GENRE_COUNT, FILTER_BY_DIRECTOR,

    STATISTIC_BY_GENRE, STATISTIC_BY_DIRECTOR,
}
